### ISSUE TITLE
release.yml に composerの実行を追加

### ISSUE THREAD

**Issue by kutsu123** [kutsu123/github-release-test#21]
```
#composerの実施
    - name: Composer install
      uses: docker://composer:1.9.1
      with:
        args: install
```

yarnの処理の後でOK
